name: auvid
description: "Audio and Video Downloader - Simple, Fast, Beautiful"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  http: ^1.2.2
  path: ^1.9.1
  shared_preferences: ^2.3.3
  file_picker: ^8.1.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_icon.png
